version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: nome_do_banco
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      # Garante que DATABASE_URL usa o host 'db' para o container backend conectar ao Postgres
       DATABASE_URL: postgresql://usuario:senha@db:5432/nome_do_banco




    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Se o frontend se comunica com o backend dentro do Docker, pode ser http://backend:8000
      # Se rodar no host, localhost funciona
      VITE_BACKEND_URL: http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
