#!/bin/bash

# Campaign Automation Service - Deployment Script
echo "🚀 Campaign Automation Service - Deployment Guide"
echo "================================================="
echo ""

echo "📋 Service Summary:"
echo "   Service Name: campaign_automation_service"
echo "   Port: 8014"
echo "   Framework: FastAPI (Python 3.11)"
echo "   Database: PostgreSQL (shared)"
echo "   Cache: Redis (database 14)"
echo "   Queue: Celery"
echo ""

echo "🐳 Docker Commands:"
echo "   Build Image:"
echo "     docker build -t campaign-automation ./campaign_automation_service"
echo ""
echo "   Run Single Service:"
echo "     docker-compose up campaign_automation_service"
echo ""
echo "   Run All Services:"
echo "     docker-compose up"
echo ""

echo "🌐 Service Endpoints:"
echo "   API Documentation: http://localhost:8014/docs"
echo "   Health Check: http://localhost:8014/health"
echo "   Service Info: http://localhost:8014/api/info"
echo "   Metrics: http://localhost:8014/metrics"
echo ""

echo "🔗 Integration Points:"
echo "   → Simulator Service (8001): Campaign simulation"
echo "   → Learning Service (8002): ML insights"
echo "   → Optimizer AI (8003): Copy optimization"
echo "   → PostgreSQL: Data persistence"
echo "   → Redis: Caching and task queues"
echo ""

echo "📊 Key Features:"
echo "   ✅ Campaign Management (CRUD + lifecycle)"
echo "   ✅ AI-Powered Optimization"
echo "   ✅ Performance Analytics"
echo "   ✅ Competitor Intelligence"
echo "   ✅ A/B Testing"
echo "   ✅ Task Automation"
echo "   ✅ Security (JWT + Rate Limiting)"
echo "   ✅ Monitoring & Health Checks"
echo ""

echo "🔧 Development Commands:"
echo "   Install dependencies: pip install -r requirements.txt"
echo "   Run tests: pytest tests/ -v"
echo "   Run locally: uvicorn src.main:app --port 8014 --reload"
echo ""

echo "🎯 Production Checklist:"
echo "   □ Set strong SECRET_KEY environment variable"
echo "   □ Configure proper DATABASE_URL"
echo "   □ Set up monitoring and alerting"
echo "   □ Configure log aggregation"
echo "   □ Set resource limits"
echo "   □ Enable HTTPS"
echo ""

echo "✅ Campaign Automation Service is ready for deployment!"
echo "   Next: Run 'docker-compose up campaign_automation_service' to start"