apiVersion: v1
kind: Service
metadata:
  name: simulator-service-external
  labels:
    app: simulator-service
spec:
  selector:
    app: simulator-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    nodePort: 30001
  type: NodePort